### ISSUE TITLE
Add message after registration

### ISSUE THREAD

**Issue by dcabo** [openbudgets/participatory-budgeting#31]
The test users of Torrelodones found it slightly confusing that there was no message/indication that an email was being sent to them after signing up. They get redirected to the main page without any additional indication. We should add a message/banner telling them to check their mail.

**Comment by esebastian** [comment]
The confirmation message exists, it's a standard flash message. The redirection after the successful sign in/sign up goes to the page from which the form was loaded (typically the home page or the voting one), and perhaps the problem is that a bit of more contrast is needed:

Confirmation message in the home page:
![screen shot 2017-05-26 at 10 53 39](https://cloud.githubusercontent.com/assets/577074/26488987/d4ed6f70-4205-11e7-81d4-e9e8dd29d060.png)

&nbsp;

Confirmation message in the voting page:
![screen shot 2017-05-26 at 11 22 26](https://cloud.githubusercontent.com/assets/577074/26489016/e7848fc4-4205-11e7-9fcc-377a2a5eb212.png)

**Comment by esebastian** [comment]
@rauldiazpoblete has changed the color used in the flash message, now it has a lot more contrast:
![screen shot 2017-05-26 at 13 09 41](https://cloud.githubusercontent.com/assets/577074/26492761/2e781b34-4216-11e7-820c-d9c3f93b631f.png)
