### ISSUE TITLE
"Area" field name

### ISSUE THREAD

**Issue by skarampatakis** [openbudgets/participatory-budgeting#49]
Area field is misleading to location info. Perhaps it could be changed to reflect its intended meaning, let say "Subject", "Concept", "Category" or similar.

**Comment by esebastian** [comment]
@skarampatakis The initial idea was to use it to encode the different functional areas of the municipality (Health, Education, Environment, etc.). If 'Area' doesn't feel right, we can change the name, but perhaps 'Department' would be best suited? Do you have anty thoughts about this @dcabo?

**Comment by dcabo** [comment]
We spent some time a while back discussing the right word for this, but can't remember exactly which ones we discarded and why. 'Department' to me sounds too institutional, as if it had to map exactly to the internal structure of the public administration, which is not always a good idea. 'Subject' or 'concept' are words I think can be used to describe what a particular proposal is about, but not so much a group of them, in my opinion. 'Category' is probably the most popular term for this type of thing.

In any case, @skarampatakis, since you're translating to Greek feel free to use the word you think is most clear, while we discuss a potential better word for the English version.

**Comment by skarampatakis** [comment]
@dcabo thank you for your time. I had already changed the Greek translation from "Περιοχή" which is the exact translation of "Area" to "Θεματική Περιοχή" which is the equivalent of the term "Theme" used by EU https://cohesiondata.ec.europa.eu/ for it's projects. 

I managed to notice such terminology issues (not many) only when I installed the platform last week so I could see the context each term was used. 

So perhaps a good candidate for the English term would be "Theme" as well.
