### ISSUE TITLE
Question: How is feeded with data?

### ISSUE THREAD

**Issue by skarampatakis** [openbudgets/participatory-budgeting#5]
Hi,
I would like to ask how is the application for participatory budgeting feeded with data? I didn't find any documentation about this. I have read in deliverables 7.2 and 7.3 that admins can ceate budget proposals but does this mean that admins should create each proposal individually? Can't we load proposals in bulk?

**Comment by dcabo** [comment]
Hi, @skarampatakis. At the moment the proposals are created only through the GUI. We intentionally wanted to wait until the pilots started so we could talk to the public officials and understand better what they needed. If they find a bulk load useful we'll add it.

**Comment by skarampatakis** [comment]
My thought on this is that it should be possible to upload data in bulk. Budgets usually come in bulk in CSV format and usually contain a lot of budget items. From my point of view it would be difficult to import on the platform all these data just using forms.

**Comment by dcabo** [comment]
The application doesn't hold budget information, it holds information about particular proposals that people can vote on.

**Comment by skarampatakis** [comment]
So the use case would be that only specific parts of the budget can get on the voting procedure?

**Comment by dcabo** [comment]
We've seen two different ways of approaching participatory budgeting: you can invite users to work over the whole local budget, both on the revenue and expenditure sides, reallocating resources; or you can ask users to choose among a list of possible budget allocations and investments. We opted for the latter, due to its more widespread adoption across Europe: it's the way it's done in Paris and Madrid, for example, while it's hard to find working examples of the former.

The tool reflects this decision: you don't vote on how much money should go to Education vs. Police, for example, you vote on whether you want the city to build a particular park, or a bicycle path, or a library and so on...

**Comment by cecilaki** [comment]
A reason why it's not usually done the other way around, at least in France, is, by Constitution, citizens are not given the power to decide over budget allocation by direct democracy, only elected officials can do it, works at both national and local level (municipal council or parliament). 

To decide on how much money should go to Education, Police or Health, you need to change the Constitution first, and then reduce/share the power of elected and parliament. Not sure they would agree even if it sounds like a good way to practice direct democracy :)
